var child = [
  { 'dupe': false, 'type': 4, 'name': 'docs', 'dir': 'c0', 'linked': 2, 'url': 'http://localhost/dashboard/docs/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 19, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'etc', 'dir': 'c1', 'linked': 1, 'url': 'http://localhost/dashboard/etc/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 2, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'images', 'dir': 'c2', 'linked': 2, 'url': 'http://localhost/dashboard/images/', 'fetched': true, 'code': 200, 'len': 7472, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'ISO-8859-1', 'missing': false, 'csens': false, 'child_cnt': 34, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x6d8b5058 },
  { 'dupe': false, 'type': 4, 'name': 'javascripts', 'dir': 'c3', 'linked': 2, 'url': 'http://localhost/dashboard/javascripts/', 'fetched': true, 'code': 200, 'len': 1141, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'ISO-8859-1', 'missing': false, 'csens': false, 'child_cnt': 4, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x7a604cfb },
  { 'dupe': false, 'type': 4, 'name': 'stylesheets', 'dir': 'c4', 'linked': 2, 'url': 'http://localhost/dashboard/stylesheets/', 'fetched': true, 'code': 200, 'len': 1565, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'ISO-8859-1', 'missing': false, 'csens': false, 'child_cnt': 6, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xafd72d0d },
  { 'dupe': false, 'type': 8, 'name': 'faq.html', 'dir': 'c5', 'linked': 2, 'url': 'http://localhost/dashboard/faq.html', 'fetched': true, 'code': 200, 'len': 20624, 'decl_mime': 'text/html', 'sniff_mime': 'text/html', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 2, 0 ], 'sig': 0xa0fd5 },
  { 'dupe': false, 'type': 8, 'name': 'howto.html', 'dir': 'c6', 'linked': 2, 'url': 'http://localhost/dashboard/howto.html', 'fetched': true, 'code': 200, 'len': 5972, 'decl_mime': 'text/html', 'sniff_mime': 'text/html', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 2, 0 ], 'sig': 0xa0fd5 },
  { 'dupe': false, 'type': 8, 'name': 'index.html', 'dir': 'c7', 'linked': 2, 'url': 'http://localhost/dashboard/index.html', 'fetched': true, 'code': 200, 'len': 7575, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': false, 'type': 16, 'name': 'phpinfo.php', 'dir': 'c8', 'linked': 2, 'url': 'http://localhost/dashboard/phpinfo.php', 'fetched': true, 'code': 200, 'len': 97326, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 1, 0, 0 ], 'sig': 0x211a7516 },
  { 'dupe': false, 'type': 32, 'name': 'manager-linux-x64.run', 'dir': 'c9', 'linked': 1, 'url': 'http://localhost/dashboard/manager-linux-x64.run', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'manager-linux.run', 'dir': 'c10', 'linked': 1, 'url': 'http://localhost/dashboard/manager-linux.run', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'xampp-linux-*-installer.run', 'dir': 'c11', 'linked': 1, 'url': 'http://localhost/dashboard/xampp-linux-*-installer.run', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 }
];
